{
 "title": "VoidMocks",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "system", "label": "system", "query": { "query": "label_values(system)" } },
   {
    "name": "mock",
    "query": {
     "query": "label_values(mock_config{system=\"$system\"},mock)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total requests",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "mock_calls_total{system=\"$system\", mock=~\"$mock\"}",
     "legendFormat": "{{mock}}"
    }
   ]
  },
  {
   "title": "Mocks count",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(mock_config)", "legendFormat": "total mocks" },
    {
     "expr": "sum(mock_config{system=\"$system\"})",
     "legendFormat": "mocks by system"
    }
   ]
  },
  {
   "title": "Mocks",
   "type": "table",
   "description": "mocks by system",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mock_config{system=\"$system\", mock=~\"$mock\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "mock_tpm{system=\"$system\", mock=~\"$mock\"}",
     "legendFormat": "{{mock}}"
    }
   ]
  },
  {
   "title": "Mocks call",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "mock_calls_total{system=\"$system\", mock=~\"$mock\"}",
     "legendFormat": "{{mock}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "description": "averaged per minute",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "mock_tpm{system=\"$system\", mock=~\"$mock\"} / 60",
     "legendFormat": "{{mock}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "mock_max_seconds{system=\"$system\", mock=~\"$mock\"}",
     "legendFormat": "{{mock}} - max"
    },
    {
     "expr": "mock_p99_seconds{system=\"$system\", mock=~\"$mock\"}",
     "legendFormat": "{{mock}} 99%"
    },
    {
     "expr": "mock_p95_seconds{system=\"$system\", mock=~\"$mock\"}",
     "legendFormat": "{{mock}} 95%"
    },
    {
     "expr": "mock_p90_seconds{system=\"$system\", mock=~\"$mock\"}",
     "legendFormat": "{{mock}} 90%"
    }
   ]
  }
 ]
}